### PR TITLE
Update to 0.3.0 and rerender

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
I hope you don't mind that I added you as a recipe maintainer here @wesm in case you want to do this yourself for this library at some point

**Comment by wesm** [comment]
no problem

**Comment by isuruf** [comment]
Can this be a `noarch: python` package?

**Comment by mariusvniekerk** [comment]
Due to different dependencies between `win` and `not win` sadly no

**Comment by isuruf** [comment]
Ah. `sasl` is only available for linux

**Comment by mariusvniekerk** [comment]
Also it's not on conda-forge.  We should probably make a recipe for it

**Comment by ericdill** [comment]
> Also it's not on conda-forge. We should probably make a recipe for it

Add a package request on the staged recipes issue tracker. Maybe we will get it for free :grinning:

**Pull request merged**
